#!/bin/bash

home="/srv"
app="rutorrent.tigris.id.au"
mailto="danial"

new_tag=RELEASE-$(date +%Y%m%dT%H%M%S)
old_tag=$(git tag -l RELEASE* | sort -r | head -n1)
old_tag=${old_tag:-"HEAD^"}
daemons=""

restart_daemons() {
  config=$(git diff $old_tag | grep "^--- a/config/nginx/$env")
  if [ "x$config" != "x" ]; then
    daemons="$daemons nginx"
    sudo /etc/init.d/nginx reload
  fi
}

print_changelog() {
  cat<<EOM

Hi,

$app has been updated with the following changes

====================================================

$(git log --stat --no-color $old_tag..HEAD)

EOM
}

cd $home/$app
restart_daemons

git tag $new_tag
print_changelog | mail -s "Restarted $app" $mailto
