#!/bin/bash

home="/srv"
app="rutorrent.tigris.id.au"
mailto="danial"

new_tag=RELEASE-$(date +%Y%m%dT%H%M%S)
old_tag=$(git tag -l RELEASE* | sort -r | head -n1)
old_tag=${old_tag:-"HEAD^"}
daemons=""

update_cron() {
  sudo cp config/cron/* /etc/cron.d
  sudo chown root.root /etc/cron.d/*
}

restart_daemons() {
  config=$(git diff $old_tag | grep "^+++ b/config/lighttpd")
  if [ "x$config" != "x" ]; then
    sudo cp config/lighttpd/*.conf /etc/lighttpd/conf-enabled
    sudo service lighttpd reload > /dev/null
    daemons="$daemons lighttpd"
  fi

  config=$(git diff $old_tag | grep "^+++ b/config/rtorrent")
  if [ "x$config" != "x" ]; then
    pid=$(cat /home/danial/.rtorrent/session/rtorrent.lock | awk -F: '{print($2)}' | sed "s/[^0-9]//g")
    if ps -A | grep -sq ${pid}.*rtorrent ; then
      kill -INT $pid
    fi
    cp config/rtorrent/.rtorrent.rc /home/danial
    sleep 5
    /usr/bin/screen -fa -d -m -S rtorrent /usr/local/bin/rtorrent
    daemons="$daemons rtorrent"
  fi
}

fix_permissions() {
  sudo chown -R danial .
  sudo chgrp -R www-data public/share
  sudo chmod -R g+w public/share
}

create_directories() {
  mkdir -p public/conf/users
  mkdir -p public/share/torrents
  mkdir -p public/share/users
  mkdir -p public/share/settings
}

print_changelog() {
  cat<<EOM

Hi,

$app has been updated with the following changes

The following daemons were reloaded/restarted:

   ${daemons:-"None restarted."}

====================================================

$(git log --stat --no-color $old_tag..HEAD)

EOM
}

cd $home/$app
update_cron
create_directories
restart_daemons
fix_permissions

git tag $new_tag
print_changelog | mail -s "Restarted $app" $mailto
